config/routes.rb
Rails.application.routes.draw do

  devise_for :administrators, controllers: { sessions: 'administrators/sessions' }
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#home"
  get 'events/new_event_option', to: "events#new_event_option", as: :new_event_event_option_otf

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :events do
        resources :comments
      end
    end
  end
  resources :users do
    resources :events
  end
  resources :mailboxes do
    resources :messages, shallow: true
  end

  resources :profiles

  resources :events do
    resources :reports
    resources :organizations
    resources :comments, shallow: true do
      resources :replies, shallow: true
    end
    resources :event_options, shallow: true do
      resources :event_votes, shallow: true
    end
    resources :event_votes
    resources :event_organizations
    resources :event_guests
  end
  resources :searches
  resources :organizations
  resources :organization_users

  match 'comments/:id/edit', controller: 'comments', action: 'update', via: 'post'


  resources :users, defaults: { format: :html }
  resources :comments, defaults: { format: :html }
  resources :events, defaults: { format: :html}
  resources :event_options, defaults: { format: :html}
  resources :mailboxes, defaults: { format: :html}
  resources :messages, defaults: { format: :html}
  resources :organizations, defaults: { format: :html}
  resources :profiles, defaults: {format: :html}
  resources :event_organizations, defaults: {format: :html}
  resources :event_guests, defaults: {format: :html}
  resources :organization_users, defaults: {format: :html}
  resources :event_votes, defaults: {format: :html}
  resources :replies, defaults: {format: :html}
  resources :reports, defaults: {format: :html}
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :event
  has_many :replies, dependent: :destroy

  accepts_nested_attributes_for :replies, allow_destroy: true
end

app/controllers/api/v1/comments_controller.rb
class API::V1::CommentsController < APIController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    #@comments = Comment.all
    @comments = Comment.where(event_id: params[:event_id]) #fuera del API esta distinto
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    #@comment = Comment.find(params[:id])
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    @comment.user = User.find(params[:user_id])
    @comment.event = Event.find(params[:event_id])

    #respond_to do |format|
    if @comment.save
      #format.html { redirect_to @event, notice: 'Event was successfully created.' }
      #format.json { render :show, status: :created, location: @event }
      render :show, status: :created, location: @event
    else
      #format.html { render :new }
      #format.json { render json: @event.errors, status: :unprocessable_entity }
      render json: @event.errors, status: :unprocessable_entity
    end
      #end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    if @comment.update(comment_params)
      render :show, status: :ok, location: api_v1_event_comments_url(@comment)
    else
      render json: @comment.errors, status: :unprocessable_entity
    end
    #respond_to do |format|
    # if @comment.update(comment_params)
        #format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        #format.json { render :show, status: :ok, location: @comment }
    # else
    #   format.html { render :edit }
    #   format.json { render json: @comment.errors, status: :unprocessable_entity }
    # end
    #end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    head :no_content
    puts ('The event was deleted succesfully!')
    #respond_to do |format|
    # format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
    # format.json { head :no_content }
    #end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_comment
    @comment = Comment.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def comment_params
    #params.fetch(:comment, {})
    params.fetch(:comment, {}).permit(:id, :user, :event, :message)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.where(event_id: params[:event_id])
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find(params[:id])
  end

  # GET /comments/new
  def new
    @event = Event.find(params[:event_id])
    @comment = Comment.new

  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
    @event = @comment.event
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        @event = @comment.event
        format.html { redirect_to @event, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        @event = @comment.event
        format.html { redirect_to @event, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @event = @comment.event
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @event, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.fetch(:comment, {}).permit(:user_id, :event_id, :message)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_with model: @comment, local: true do |form| %>
  <%= form.hidden_field :event_id, value: @event.id %>

  <%if user_signed_in? %>
    <%= form.hidden_field :user_id, value: current_user.id %>
  <%elsif administrator_signed_in? %>
    <div class="form-group">
      <%@event_users = @event.users %>
      <%= form.label :user_id %>
      <%= form.collection_select :user_id, @event_users.all.order(:username), :id, :username %>
    </div>
  <%end %>
  <div class="form-group">
    <%= form.label :message %>
    <%= form.text_field :message, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.submit class: ["btn", "btn-primary"] %>
    <%= link_to "Back", :back, class: ["btn", "btn-secondary"] %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<div class="row ml-0 mt-3">
  <h2>Edit Comment</h2>
</div>
<%= render partial: "form",
           locals: {
               comment: @comment,
               event: @event,
               submit_btn_text: "Update",
           } %>

<br>

<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.event.title %></td>
        <td><%= comment.message %></td>
        <%if administrator_signed_in? or current_person = comment.user%>
          <td><%= link_to 'Show', comment %></td>
          <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
          <td><%= link_to 'Delete', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%else %>
          <td><%= link_to 'Show', comment %></td>
        <%end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<div class="row ml-0 mt-3">
  <h2>Add comment</h2>
</div>
<div class="row ml-0 mt-2">
  <p>Enter comment for the event:</p>
</div>
<div class="row ml-0 mt-2">
  <%= render 'form', locals: { user: @user, event: @event, comment: @comment } %>
</div>
<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>
<table>
  <thead>
  <tr>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <tr>
    <td>comments</td>
  </tr>
  </tbody>
</table>

<br>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>