config/routes.rb
Rails.application.routes.draw do

  devise_for :administrators, controllers: { sessions: 'administrators/sessions' }
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#home"
  get 'events/new_event_option', to: "events#new_event_option", as: :new_event_event_option_otf

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :events do
        resources :comments
      end
    end
  end
  resources :users do
    resources :events
  end
  resources :mailboxes do
    resources :messages, shallow: true
  end

  resources :profiles

  resources :events do
    resources :reports
    resources :organizations
    resources :comments, shallow: true do
      resources :replies, shallow: true
    end
    resources :event_options, shallow: true do
      resources :event_votes, shallow: true
    end
    resources :event_votes
    resources :event_organizations
    resources :event_guests
  end
  resources :searches
  resources :organizations
  resources :organization_users

  match 'comments/:id/edit', controller: 'comments', action: 'update', via: 'post'


  resources :users, defaults: { format: :html }
  resources :comments, defaults: { format: :html }
  resources :events, defaults: { format: :html}
  resources :event_options, defaults: { format: :html}
  resources :mailboxes, defaults: { format: :html}
  resources :messages, defaults: { format: :html}
  resources :organizations, defaults: { format: :html}
  resources :profiles, defaults: {format: :html}
  resources :event_organizations, defaults: {format: :html}
  resources :event_guests, defaults: {format: :html}
  resources :organization_users, defaults: {format: :html}
  resources :event_votes, defaults: {format: :html}
  resources :replies, defaults: {format: :html}
  resources :reports, defaults: {format: :html}
end

app/models/mailbox.rb
class Mailbox < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :destroy

  accepts_nested_attributes_for :messages
end

app/controllers/mailboxes_controller.rb
class MailboxesController < ApplicationController
  before_action :set_mailbox, only: [:show, :edit, :update, :destroy]

  # GET /mailboxes
  # GET /mailboxes.json
  def index
    @mailbox = Mailbox.find(params[:id])
    @messages = @mailbox.messages
  end

  # GET /mailboxes/1
  # GET /mailboxes/1.json
  def show
    #@user_mailbox = Mailbox.where(user_id: params[:user_id])
    #@mailbox = Mailbox.find(params[:id])
    #@messages = @mailbox.messages
  end

  # GET /mailboxes/new
  def new
    @mailbox = Mailbox.new
  end

  # GET /mailboxes/1/edit
  def edit
  end

  # POST /mailboxes
  # POST /mailboxes.json
  def create
    @mailbox = Mailbox.new(mailbox_params)

    respond_to do |format|
      if @mailbox.save
        format.html { redirect_to @mailbox, notice: 'Mailbox was successfully created.' }
        format.json { render :show, status: :created, location: @mailbox }
      else
        format.html { render :new }
        format.json { render json: @mailbox.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mailboxes/1
  # PATCH/PUT /mailboxes/1.json
  def update
    respond_to do |format|
      if @mailbox.update(mailbox_params)
        format.html { redirect_to @mailbox, notice: 'Mailbox was successfully updated.' }
        format.json { render :show, status: :ok, location: @mailbox }
      else
        format.html { render :edit }
        format.json { render json: @mailbox.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mailboxes/1
  # DELETE /mailboxes/1.json
  def destroy
    @mailbox.destroy
    respond_to do |format|
      format.html { redirect_to mailboxes_url, notice: 'Mailbox was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mailbox
      @mailbox = Mailbox.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mailbox_params
      params.fetch(:mailbox, {})
    end
end

app/helpers/mailboxes_helper.rb
module MailboxesHelper
end

app/views/mailboxes/_form.html.erb
<%= form_with(model: mailbox, local: true) do |form| %>
  <% if mailbox.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mailbox.errors.count, "error") %> prohibited this mailbox from being saved:</h2>

      <ul>
        <% mailbox.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/mailboxes/edit.html.erb
<h1>Editing Mailbox</h1>

<%= render 'form', mailbox: @mailbox %>

<%= link_to 'Show', @mailbox %> |
<%= link_to 'Back', mailboxes_path %>

app/views/mailboxes/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%=@user.profile.name%> Mailbox</h1>
<table>
  <thead>
    <tr>
      <th><h2>Messages</h2></th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><h3>From: <%=message.user.username%></h3></td>
        <td><%=message.content%></td>
        <td><%= link_to 'Show', mailbox %></td>
        <td><%= link_to 'Edit', edit_mailbox_path(mailbox) %></td>
        <td><%= link_to 'Delete'%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mailbox', new_mailbox_path %>

app/views/mailboxes/new.html.erb
<h1>Compose new message</h1>

<%= render 'form', mailbox: @mailbox %>

<%= link_to 'Back', '/mailboxes/1' %>

app/views/mailboxes/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="row">
    <!-- BEGIN INBOX -->
    <div class="col-md-12">
      <div class="grid email">
        <div class="grid-body">
          <div class="row">
            <!-- BEGIN INBOX MENU -->
            <div class="col-md-3">
              <h2 class="grid-title"><i class="fa fa-inbox"></i>Mailbox</h2>
              <button type="button" class="btn btn-outline-secondary"><%= link_to 'Compose new message', new_mailbox_message_path(current_user.mailbox) %></button>
            </div>
            <!-- END INBOX MENU -->

            <!-- BEGIN INBOX CONTENT -->
            <div class="col-md-9">
              <div class="row">

                <div class="col-md-6 search-form">
                  <form action="#" class="text-right">
                    <div class="input-group">
                      <input type="text" class="form-control input-sm" placeholder="Search">
                      <span class="input-group-btn">
                        <button type="submit" name="search" class="btn_ btn-primary btn-sm search"><i class="fa fa-search"></i></button></span>
                    </div>
                  </form>
                </div>
              </div>

              <div class="padding"></div>

              <div class="table-responsive">
                <table class="table">
                  <tbody>
                  <% current_user.messages.each do |message| %>
                    <tr>
                      <td class="action"><input type="checkbox" /></td>
                      <td class="action"><i class="fa fa-star-o"></i></td>
                      <td class="action"><i class="fa fa-bookmark-o"></i></td>
                      <td><h5 class="card-text"><%=message.mailbox.user.username%></h5></td>
                      <td class="subject" class="card-text"><a href="#"><%=message.content%> </a></td>
                      <td class="time" class="card-text"><%=message.created_at %></td>
                      <td><%= link_to 'Show', message_path(message) %></td>
                      <td><%= link_to 'Delete', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                    </tr>
                  <% end %>
                  </tbody></table>
              </div>

              <ul class="pagination">
                <li class="disabled"><a href="#">«</a></li>
                <li class="active"><a href="#">1</a></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">4</a></li>
                <li><a href="#">5</a></li>
                <li><a href="#">»</a></li>
              </ul>
            </div>
            <!-- END INBOX CONTENT -->

          </div>
        </div>
      </div>
    </div>
    <!-- END INBOX -->
  </div>
</div>

<%= link_to 'Back to home', root_path %>