config/routes.rb
Rails.application.routes.draw do

  devise_for :administrators, controllers: { sessions: 'administrators/sessions' }
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#home"
  get 'events/new_event_option', to: "events#new_event_option", as: :new_event_event_option_otf

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :events do
        resources :comments
      end
    end
  end
  resources :users do
    resources :events
  end
  resources :mailboxes do
    resources :messages, shallow: true
  end

  resources :profiles

  resources :events do
    resources :reports
    resources :organizations
    resources :comments, shallow: true do
      resources :replies, shallow: true
    end
    resources :event_options, shallow: true do
      resources :event_votes, shallow: true
    end
    resources :event_votes
    resources :event_organizations
    resources :event_guests
  end
  resources :searches
  resources :organizations
  resources :organization_users

  match 'comments/:id/edit', controller: 'comments', action: 'update', via: 'post'


  resources :users, defaults: { format: :html }
  resources :comments, defaults: { format: :html }
  resources :events, defaults: { format: :html}
  resources :event_options, defaults: { format: :html}
  resources :mailboxes, defaults: { format: :html}
  resources :messages, defaults: { format: :html}
  resources :organizations, defaults: { format: :html}
  resources :profiles, defaults: {format: :html}
  resources :event_organizations, defaults: {format: :html}
  resources :event_guests, defaults: {format: :html}
  resources :organization_users, defaults: {format: :html}
  resources :event_votes, defaults: {format: :html}
  resources :replies, defaults: {format: :html}
  resources :reports, defaults: {format: :html}
end

app/models/search.rb
class Search < ApplicationRecord
  def users
    @users = find_users
  end

  def profiles
    @profiles = find_profiles
  end

  def events
    @events =  find_events
  end

  def organizations
    @organizations = find_organizations
  end

  private

  def find_organizations
    organizations = Organization.order(created_at: :desc)
    organizations = organizations.where("name like ?", "%#{keywords}%", "%#{keywords}%") if keywords.present?
    organizations
  end

  def find_events
    events = Event.order(created_at: :desc)
    events = events.where("title like ? OR description like?", "%#{keywords}%") if keywords.present?
    events
  end

  def find_profiles
    profile = Profile.order(:name)
    profiles = profiles.where("name like ?", "%#{keywords}%") if keywords.present?
    users
  end

  def find_users
    users = User.order(:username)
    users = users.where("username like ?", "%#{keywords}%") if keywords.present?
    users
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :set_search, only: [:show, :edit, :update, :destroy]

  # GET /searches
  # GET /searches.json
  def index
    @searches = Search.all
  end

  # GET /searches/1
  # GET /searches/1.json
  def show
    @search = Search.find(params[:id])
  end

  # GET /searches/new
  def new
    @search = Search.new
  end

  # GET /searches/1/edit
  def edit
  end

  # POST /searches
  # POST /searches.json
  def create
    @search = Search.new(search_params)

    respond_to do |format|
      if @search.save
        format.html { redirect_to @search, notice: 'Search was successfully created.' }
        format.json { render :show, status: :created, location: @search }
      else
        format.html { render :new }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /searches/1
  # PATCH/PUT /searches/1.json
  def update
    respond_to do |format|
      if @search.update(search_params)
        format.html { redirect_to @search, notice: 'Search was successfully updated.' }
        format.json { render :show, status: :ok, location: @search }
      else
        format.html { render :edit }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /searches/1
  # DELETE /searches/1.json
  def destroy
    @search.destroy
    respond_to do |format|
      format.html { redirect_to searches_url, notice: 'Search was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_search
      @search = Search.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def search_params
      params.fetch(:search, {}).permit!
    end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_form.html.erb
<%= form_with(model: search, local: true) do |form| %>
  <% if search.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(search.errors.count, "error") %> prohibited this search from being saved:</h2>

      <ul>
        <% search.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/searches/edit.html.erb
<h1>Editing Search</h1>

<%= render 'form', search: @search %>

<%= link_to 'Show', @search %> |
<%= link_to 'Back', searches_path %>

app/views/searches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Searches</h1>

<%= form_tag  %>
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @searches.each do |search| %>
      <tr>
        <td><%= link_to 'Show', search_path(search) %></td>
        <td><%= link_to 'Edit', edit_organization_path(organization) %></td>
        <td><%= link_to 'Destroy', organization, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Search', new_search_path %>

app/views/searches/new.html.erb
<h1>New Search</h1>

<%= render 'form', search: @search %>

<%= link_to 'Back', searches_path %>

app/views/searches/show.html.erb
<p id="notice"><%= notice %></p>
<hi>Search Results</hi>

<%= render @search.organizations%>
<%= link_to 'Edit', edit_search_path(@search) %>
<%= link_to 'Back', searches_path %>