config/routes.rb
Rails.application.routes.draw do

  devise_for :administrators, controllers: { sessions: 'administrators/sessions' }
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#home"
  get 'events/new_event_option', to: "events#new_event_option", as: :new_event_event_option_otf

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :events do
        resources :comments
      end
    end
  end
  resources :users do
    resources :events
  end
  resources :mailboxes do
    resources :messages, shallow: true
  end

  resources :profiles

  resources :events do
    resources :reports
    resources :organizations
    resources :comments, shallow: true do
      resources :replies, shallow: true
    end
    resources :event_options, shallow: true do
      resources :event_votes, shallow: true
    end
    resources :event_votes
    resources :event_organizations
    resources :event_guests
  end
  resources :searches
  resources :organizations
  resources :organization_users

  match 'comments/:id/edit', controller: 'comments', action: 'update', via: 'post'


  resources :users, defaults: { format: :html }
  resources :comments, defaults: { format: :html }
  resources :events, defaults: { format: :html}
  resources :event_options, defaults: { format: :html}
  resources :mailboxes, defaults: { format: :html}
  resources :messages, defaults: { format: :html}
  resources :organizations, defaults: { format: :html}
  resources :profiles, defaults: {format: :html}
  resources :event_organizations, defaults: {format: :html}
  resources :event_guests, defaults: {format: :html}
  resources :organization_users, defaults: {format: :html}
  resources :event_votes, defaults: {format: :html}
  resources :replies, defaults: {format: :html}
  resources :reports, defaults: {format: :html}
end

app/models/organization.rb
class Organization < ApplicationRecord
  belongs_to :user
  has_many :event_organizations, dependent: :destroy
  has_many :events, through: :event_organizations, dependent: :destroy
  has_many :organization_users, dependent: :destroy
  has_many :users, through: :organization_users
  has_one_attached :picture, dependent: :destroy

  accepts_nested_attributes_for :organization_users

  after_create :org_user

  def self.search(search)
    if search
      organizations = Organization.where("name LIKE ?" , "%#{search}%")
    else
      organizations = Organization.all
    end
  end

  def org_user
    OrganizationUser.create!(user_id: self.user.id, organization_id: self.id)
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.search(params[:search])
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
    @organization = Organization.find(params[:id])
    @events = @organization.events
    @participants = @organization.organization_users
  end

  # GET /organizations/new
  def new
    @user = User.first
    @organization = Organization.new
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params)

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url, notice: 'Organization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def organization_params
      params.fetch(:organization, {}).permit( :id, :name, :user_id, :description, :picture, event_organization_attributes: [:id, :event_id, :priv_or_pub], organization_users_attributes: [:id, :organization_id])
    end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.erb
<div class="row ml-0">
  <%= form_with model: organization, local: true do |form| %>

    <% if action_name == "new" %>
      <%if user_signed_in? %>
        <%= form.hidden_field :user_id, value: current_user.id %>
      <%elsif administrator_signed_in? %>
        <div class="form-group">
          <%= form.label :user_id %>
          <%= form.collection_select :user_id, User.all.order(:username), :id, :username %>
        </div>
      <%end %>
    <%end %>

    <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :description %>
      <%= form.text_area :description, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :picture %>
      <%= form.file_field :picture %>
    </div>
    <div class="form-group mt-2">
      <%= form.submit submit_btn_text, class: ["btn", "btn-primary"] %>
      <%= link_to "Back", :back, class: ["btn", "btn-secondary"] %>
    </div>
  <% end %>
</div>

app/views/organizations/edit.html.erb
<h1>Editing Organization</h1>

<div class="row ml-0 mt-3">
  <h2>Edit "<%=@organization.name%>" Organization</h2>
</div>
<div class="row ml-0 mt-2">
  <p>Enter the following to edit the "<%=@organization.name%>" event:</p>
</div>
<%= render partial: "form",
           locals: {
               organization: @organization,
               submit_btn_text: "Update",
           } %>


<%= link_to 'Back', organizations_path %>

app/views/organizations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Organizations</h1>


<%= form_tag organizations_path, :method => "get" do %>
  <%=label_tag(:search, "Organization Name:") %>
  <%=text_field_tag :search, params[:search] %>
  <%=submit_tag("Search", :name => nil) %>
<%end %>

<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Administrator</th>
    <th>Created at</th>
    <th>Updated at</th>
    <th colspan="3"></th>
  </tr>
  </thead>
  <tbody>
  <% @organizations.each do |organization| %>
    <tr>
      <td><%= organization.name %></td>
      <td><%= organization.user.profile.name %></td>
      <td><%= organization.created_at %></td>
      <td><%= organization.updated_at %></td>
      <td><%= link_to 'Show', organization_path(organization) %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<div class="row ml-0 mt-2 mb-3">
  <%if administrator_signed_in? %>
    <%= link_to "Create Organization", new_organization_path, class: ["btn", "btn-primary"] %>
  <%end %>
</div>

<%= link_to 'Back to home', root_path %>

app/views/organizations/new.html.erb
<h1>New Organization</h1>
<div class="row ml-0 mt-3">
  <h2>New organization</h2>
</div>
<div class="row ml-0 mt-2">
  <p>Enter the following to create an Event:</p>
</div>
<%= render partial: "form",
           locals: {
               organization: @organization,
               submit_btn_text: "Create",
           } %>


<%= link_to 'Back', organizations_path %>

app/views/organizations/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="leftcolumn">
    <div class="card">
      <h2><%= @organization.name %></h2>
      <h5><%= @organization.description %></h5>
      <div class="row ml-0 mt-3">
        <% if @organization.picture.attached? == true %>
          <button type="button" class="btn btn-primary" data-toggle="modal" data-target=".bd-example-modal-lg" style="width:400px;" ><%= image_tag(@organization.picture, height: "50%", width: "50%") %></button>
          <div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
            <div class="modal-dialog" style="width:800px;" >
              <div class="modal-content">
                <div class ="modal-header"><button type='button' class='close' style='font-size:10px' data-dismiss='modal'>×</button></div>
                <%= image_tag(@organization.picture, height: "50%", width: "80%") %>
              </div>
            </div>
          </div>
        <%end %>
        <% if @organization.picture.attached? == false %>
          <button type="button" class="btn btn-primary" data-toggle="modal" data-target=".bd-example-modal-lg" style="width:400px;" ><%= image_tag("no_image.png", class: "card-img-top", width: "100%", background: "#55595c", color: "#eceeef") %></button>
          <div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
            <div class="modal-dialog" style="width:800px;">
              <div class="modal-content">
                <div class ="modal-header"><button type='button' class='close' style='font-size:10px' data-dismiss='modal'>×</button></div>
                <%= image_tag("no_image.png") %>
              </div>
            </div>
          </div>
        <%end %>
      </div>
    </div>
    <div class="card">
      <h2>Events</h2>
      <% @events.each do |event| %>
        <%if (event.presence_in @organization.events) != nil and event.privorpub = 2 %>
          <%= render partial: 'events/event_tile', locals: { event: event } %>
        <%end %>
      <% end %>
    </div>

    <div class="card">
      <h2>Users in organization</h2>
      <%@participants.each do |participant|%>
        <p><%=participant.user.username%> <%=link_to 'See profile', user_path(participant.user)%></p>
      <%end%>
    </div>

    <div class="card">
      <h3>About us</h3>
      <p>Contact us at organization@organization.com</p>
    </div>
  </div>

</div>



<br>

<div class="row ml-0 mt-2 mb-3">
  <%= link_to 'See all organizations', '/organizations', class: ["btn", "btn-primary"] %>
</div>

<%if can? :edit, @organization %>
  <div class="row ml-0 mt-2 mb-3">
    <%= link_to 'Edit', edit_organization_path(@organization), class: ["btn", "btn-primary"] %> |
  </div>
<%end %>
<%if can? :delete, @organization %>
  <div class="row ml-0 mt-2 mb-3">
    <%= link_to "Destroy", @organization, method: :delete, data: { confirm: 'Are you sure?' }, class:  ["btn", "btn-primary"]  %> |
  </div>
<%end %>


<%= link_to 'Back', '/organizations' , class: ["btn", "btn-primary"]%>